name: Deploy to Remote Server
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3
      # Iniciar sesión en DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # Transferir el archivo compose.yml al servidor remoto
      - name: Transfer compose.yml to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          source: ./compose.yml
          target: ~/deploy/
      # Desplegar la aplicación en el servidor remoto usando docker-compose
      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          script: |
            cd ~/deploy
            sudo chmod 666 /var/run/docker.sock
            docker compose down || true
            docker compose pull
            docker compose up -d